##
# General configuration (mostly used by logs)
##
environment: development
service: 42-jitsi

##
# Log configuration
##
log_level: debug
# -- sentry configuration
sentry:
  dsn: https://identifier@sentry.com/projectid
  levels:
    - error
    - fatal
    - panic
  enabled: no

##
# SlackThat configuration
##
slack_that:
  url: "http://localhost:8080"
  workspace: "42born2code"
  username: "Evaluation Master"

##
# Daemon configuration
##
warn_before: 15m # Time in duration format

##
# Consumers configuration
##
timeout: 10s
# -- api consumer configuration
http_addr: 0.0.0.0:5000

##
# Intranet API configuration
##
intra:
  app_id: --FILL ME--
  app_secret: --FILL ME--
  webhooks: --FILL:ME--
  # webhooks shall be a mapstring or a string of the form: "scale_team.create:secret_create,scale_team.update:secret_update,..."

##
# PostgreSQL configuration
##
postgres:
  host: localhost
  port: 5432
  db: postgres
  user: postgres
  password: --FILL ME--

##
# RabbitMQ configuration
##
rabbitmq:
  host: localhost
  port: 5672
  vhost: ""
  user: guest
  password: guest
  queue: webhooks_intra_42jitsi

# Deprecated configuration
email_suffix: "student.42campus.org" # Used to format room name

